# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'sf-controller'
copyright = '2021, sunfounder'
author = 'sunfounder'

# The full version, including alpha/beta/rc tags
release = '1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_js_files = [
    'https://ezblock.cc/readDocFile/custom.js',
]
html_css_files = [
    'https://ezblock.cc/readDocFile/custom.css',
]

# new
rst_epilog = """

.. |set| image:: img/icon/set.png  
    :width: 20
.. |edit| image:: img/icon/edit.png  
    :width: 20

.. |save| image:: img/icon/save.png  
    :width: 20

.. |delete| image:: img/icon/delete.png  
    :width: 20
.. |connect| image:: img/icon/connect.png  
    :width: 20
.. |sort| image:: img/icon/sort.png  
    :width: 20
.. |run| image:: img/icon/run.png  
    :width: 20
.. |radar| image:: img/icon/radar.png  
    :width: 400
.. |greyscale| image:: img/icon/greyscale.png  
    :width: 400
.. |slider| image:: img/icon/slider.png  
    :width: 400
.. |gauge| image:: img/icon/gauge.png  
    :width: 400
.. |button| image:: img/icon/button.png  
    :width: 400
.. |microphone| image:: img/icon/microphone.png  
    :width: 400
.. |number| image:: img/icon/number.png  
    :width: 400
.. |switch| image:: img/icon/switch.png  
    :width: 400
.. |joystick| image:: img/icon/joystick.png  
    :width: 400
.. |dpad| image:: img/icon/dpad.png  
    :width: 400
.. |throttle| image:: img/icon/throttle.png  
    :width: 400
.. |delete1| image:: img/icon/delete1.png  
    :width: 400
.. |bigsquare| image:: img/icon/bigsquare.png  
    :width: 30
.. |smallsquare| image:: img/icon/smallsquare.png  
    :width: 20
.. |longsquare| image:: img/icon/longsquare.png  
    :width: 60
"""